### ISSUE TITLE
duplicated key at line 265 :msg_type

### ISSUE THREAD

**Issue by Sacristan** [ebeigarts/active_merchant_first_data#4]
/Users/girts/.rvm/gems/ruby-2.2.0@cpp/gems/active_merchant_first_data-1.2.0/lib/active_merchant/billing/first_data_gateway.rb:264: warning: duplicated key at line 265 ignored: :msg_type

@ class ActiveMerchant::Billing::FirstDataGateway

```ruby
      def update_recurring(params = {})
        params = params.reverse_merge(
          :command => :p,
          :amount => 0,
          :currency => default_currency,
          :msg_type => 'SMS',
          :msg_type => 'AUTH',
          :perspayee_gen => 1,
          :perspayee_overwrite => 1
        )
        lookup_currency(params)
        requires!(params, :currency, :client_ip_addr, :description, :biller_client_id, :perspayee_expiry)
        commit(params)
      end
```

**Comment by Sacristan** [comment]
i wonder why there are two msg_type fields
 :msg_type => 'SMS',
 :msg_type => 'AUTH',

in passed params

**Comment by ebeigarts** [comment]
@Sacristan looks like a type. `:msg_type => 'SMS'` should be removed.

**Comment by Sacristan** [comment]
Pull request -> https://github.com/ebeigarts/active_merchant_first_data/pull/5
